name: ui_challenges
description: "UI Challenges"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/car_rental/
    - assets/buy_shoes/
    - assets/online_course/
    - assets/movies_directory/
    - assets/budgetting_app/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700        
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600